import { createHash, createPrivateKey, createPublicKey, sign } from "node:crypto";
import { mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const fixtureRoot = dirname(fileURLToPath(import.meta.url));
const catalogRoot = resolve(fixtureRoot, "../..");
const generatedNotice = "Development fixture generated by node catalog/fixtures/runtime-tuf/generate.mjs; DO NOT EDIT.";
const atTimeUnix = 1783900800;
const expiresUnix = 1893456000;
const outputs = new Map();

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const serialize = (value) => Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
const secretFor = (label) => createHash("sha256").update(`PUBLIC SIORB DEVELOPMENT FIXTURE KEY: ${label}`).digest();
const keyLabels = ["dev-root-a", "dev-root-b", "dev-snapshot", "dev-targets", "dev-timestamp"];
const pairs = Object.fromEntries(keyLabels.sort().map((id) => {
  const secret = secretFor(id);
  const privateKey = createPrivateKey({ key: Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), secret]), format: "der", type: "pkcs8" });
  const publicDer = createPublicKey(privateKey).export({ format: "der", type: "spki" });
  return [id, { privateKey, public: publicDer.subarray(publicDer.length - 32).toString("base64") }];
}));

const signedEnvelope = (signed, keyIds) => {
  const bytes = Buffer.from(JSON.stringify(signed));
  return {
    signed,
    signatures: keyIds.map((key_id) => ({ key_id, signature: sign(null, bytes, pairs[key_id].privateKey).toString("base64") })),
  };
};
const description = (version, bytes) => ({ version, length: bytes.length, sha256: sha256(bytes) });
const targetDescription = (bytes) => ({
  length: bytes.length,
  sha256: sha256(bytes),
  custom: { catalog_version: "2026071301", schema_version: "1.0" },
});

const rootSigned = {
  type: "root",
  spec_version: "1.0",
  version: 1,
  expires_unix: 2051222400,
  consistent_snapshot: true,
  keys: Object.fromEntries(Object.entries(pairs).map(([id, pair]) => [id, { scheme: "ed25519", public: pair.public }])),
  roles: {
    root: { key_ids: ["dev-root-a", "dev-root-b"], threshold: 2 },
    snapshot: { key_ids: ["dev-snapshot"], threshold: 1 },
    targets: { key_ids: ["dev-targets"], threshold: 1 },
    timestamp: { key_ids: ["dev-timestamp"], threshold: 1 },
  },
};
const rootEnvelope = signedEnvelope(rootSigned, ["dev-root-a", "dev-root-b"]);
const rootBytes = serialize(rootEnvelope);
const catalogBytes = await readFile(resolve(catalogRoot, "generated/catalog.json"));

const buildTargets = ({ version = 1, targetBytes = catalogBytes } = {}) => {
  const signed = {
    type: "targets",
    spec_version: "1.0",
    version,
    expires_unix: expiresUnix,
    targets: { "catalog.json": targetDescription(targetBytes) },
  };
  const envelope = signedEnvelope(signed, ["dev-targets"]);
  return { signed, envelope, bytes: serialize(envelope) };
};

const buildSnapshot = ({ version = 1, describedTargetsVersion = 1, targetsBytes } = {}) => {
  const signed = {
    type: "snapshot",
    spec_version: "1.0",
    version,
    expires_unix: expiresUnix,
    meta: { "targets.json": description(describedTargetsVersion, targetsBytes) },
  };
  const envelope = signedEnvelope(signed, ["dev-snapshot"]);
  return { signed, envelope, bytes: serialize(envelope) };
};

const buildTimestamp = ({
  version = 1,
  expires = expiresUnix,
  describedSnapshotVersion = 1,
  snapshotBytes,
  snapshotSha256,
  snapshotLength,
  signatures = true,
} = {}) => {
  const actual = description(describedSnapshotVersion, snapshotBytes);
  const signed = {
    type: "timestamp",
    spec_version: "1.0",
    version,
    expires_unix: expires,
    snapshot: {
      version: describedSnapshotVersion,
      length: snapshotLength ?? actual.length,
      sha256: snapshotSha256 ?? actual.sha256,
    },
  };
  const envelope = signedEnvelope(signed, signatures ? ["dev-timestamp"] : []);
  return { signed, envelope, bytes: serialize(envelope) };
};

const validTargets = buildTargets();
const validSnapshot = buildSnapshot({ targetsBytes: validTargets.bytes });
const validTimestamp = buildTimestamp({ snapshotBytes: validSnapshot.bytes });

function emitRepository(prefix, {
  root = rootBytes,
  timestamp = validTimestamp.bytes,
  snapshot = validSnapshot.bytes,
  snapshotFileVersion = 1,
  targets = validTargets.bytes,
  targetsFileVersion = 1,
  catalog = catalogBytes,
  expected = "success",
  expectedStage = "repository",
  rollbackState = { root: 0, timestamp: 0, snapshot: 0, targets: 0 },
}) {
  outputs.set(`${prefix}/runtime-root.json`, root);
  outputs.set(`${prefix}/timestamp.json`, timestamp);
  outputs.set(`${prefix}/${snapshotFileVersion}.snapshot.json`, snapshot);
  outputs.set(`${prefix}/${targetsFileVersion}.targets.json`, targets);
  outputs.set(`${prefix}/catalog.json`, catalog);
  outputs.set(`${prefix}/fixture.json`, serialize({
    _generated: generatedNotice,
    at_time_unix: atTimeUnix,
    rollback_state: rollbackState,
    expected,
    expected_stage: expectedStage,
  }));
}

emitRepository("valid", {});
outputs.set("../../trusted-root/runtime-root.json", rootBytes);

const expiredTimestamp = buildTimestamp({ expires: 1577836800, snapshotBytes: validSnapshot.bytes });
emitRepository("attacks/expired", { timestamp: expiredTimestamp.bytes, expected: "update.metadata.expired" });

const thresholdTimestamp = buildTimestamp({ snapshotBytes: validSnapshot.bytes, signatures: false });
emitRepository("attacks/threshold", { timestamp: thresholdTimestamp.bytes, expected: "update.threshold.not_met" });

const rollbackTimestamp = buildTimestamp({ version: 0, snapshotBytes: validSnapshot.bytes });
emitRepository("attacks/rollback", {
  timestamp: rollbackTimestamp.bytes,
  expected: "update.rollback.detected",
  rollbackState: { root: 1, timestamp: 1, snapshot: 1, targets: 1 },
});

const mixedSnapshot = buildSnapshot({ version: 2, describedTargetsVersion: 1, targetsBytes: validTargets.bytes });
const mixedTimestamp = buildTimestamp({ describedSnapshotVersion: 1, snapshotBytes: mixedSnapshot.bytes });
emitRepository("attacks/mix-match", { timestamp: mixedTimestamp.bytes, snapshot: mixedSnapshot.bytes, expected: "update.snapshot.mix_match" });

const badHashTimestamp = buildTimestamp({ snapshotBytes: validSnapshot.bytes, snapshotSha256: "00".repeat(32) });
emitRepository("attacks/metadata-hash", { timestamp: badHashTimestamp.bytes, expected: "update.hash.mismatch" });

const truncatedSnapshot = Buffer.from('{"signed":{"type":"snapshot"');
const truncationTimestamp = buildTimestamp({ snapshotBytes: truncatedSnapshot });
emitRepository("attacks/truncation", { timestamp: truncationTimestamp.bytes, snapshot: truncatedSnapshot, expected: "update.metadata.invalid" });

emitRepository("attacks/target-hash", {
  catalog: Buffer.concat([Buffer.from("["), catalogBytes.subarray(1)]),
  expected: "update.hash.mismatch",
  expectedStage: "target",
});

const targetsV2 = buildTargets({ version: 2 });
const targetsMixedSnapshot = buildSnapshot({ describedTargetsVersion: 1, targetsBytes: targetsV2.bytes });
const targetsMixedTimestamp = buildTimestamp({ snapshotBytes: targetsMixedSnapshot.bytes });
emitRepository("attacks/targets-mix-match", {
  timestamp: targetsMixedTimestamp.bytes,
  snapshot: targetsMixedSnapshot.bytes,
  targets: targetsV2.bytes,
  expected: "update.targets.mix_match",
});

const rootThresholdEnvelope = { ...rootEnvelope, signatures: [rootEnvelope.signatures[0]] };
emitRepository("attacks/root-threshold", { root: serialize(rootThresholdEnvelope), expected: "update.threshold.not_met", expectedStage: "root" });

async function listFiles(directory, prefix = "") {
  let entries;
  try { entries = await readdir(directory, { withFileTypes: true }); } catch { return []; }
  const files = [];
  for (const entry of entries) {
    const path = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...await listFiles(resolve(directory, entry.name), path));
    else files.push(path);
  }
  return files.sort();
}

const generatedOutputs = [...outputs.entries()].map(([path, bytes]) => [resolve(fixtureRoot, path), bytes]);
if (process.argv.includes("--check")) {
  const problems = [];
  const expectedWithinFixture = new Set([...outputs.keys()].filter((path) => !path.startsWith("../")));
  for (const file of await listFiles(resolve(fixtureRoot, "valid"), "valid")) if (!expectedWithinFixture.has(file)) problems.push(`unexpected fixture file: ${file}`);
  for (const file of await listFiles(resolve(fixtureRoot, "attacks"), "attacks")) if (!expectedWithinFixture.has(file)) problems.push(`unexpected fixture file: ${file}`);
  for (const [path, expected] of generatedOutputs) {
    let actual;
    try { actual = await readFile(path); } catch { problems.push(`missing generated fixture: ${path}`); continue; }
    if (!actual.equals(expected)) problems.push(`stale generated fixture: ${path}`);
  }
  if (problems.length) {
    console.error(problems.join("\n"));
    process.exitCode = 1;
  } else {
    console.log(`runtime TUF fixtures current: 1 valid repository, 9 attack repositories`);
  }
} else {
  await rm(resolve(fixtureRoot, "valid"), { recursive: true, force: true });
  await rm(resolve(fixtureRoot, "attacks"), { recursive: true, force: true });
  for (const [path, contents] of generatedOutputs) {
    await mkdir(dirname(path), { recursive: true });
    const temporary = `${path}.tmp`;
    await writeFile(temporary, contents);
    await rename(temporary, path);
  }
  console.log(`generated runtime TUF fixtures: 1 valid repository, 9 attack repositories`);
}
